language: C++

matrix:
  include:
    - os: osx
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      compiler: g++-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
script:
  - if["$TRAVIS_OS_NAME" = 'osx'];   then  make; fi
  - if["$TRAVIS_OS_NAME" = 'linux']; then  CXX=g++-7 make; fi
