language: C++

matrix:
  include:
    - os: osx
      osx_image: xcode9
      dist: trusty
      compiler: clang

    - os: linux
      dist: trusty
      compiler: gcc
      env: CXX=g++-7
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-7
script:
  make -j9
