language: C++

matrix:
  include:
    - os: osx
      osx_image: xcode9
      dist: trusty
      compiler: clang

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: g++-7

script: 
    - if ["$CXX" == "g++" ]; then export CXX="g++-7"; fi
    - make -j9
